binderhub:
  rbac:
    enabled: true

  config:
    BinderHub:
      use_registry: true
      build_image: jupyter/repo2docker:9766c954
      per_repo_quota: 100

  jupyterhub:
    cull:
      # cull every 11 minutes so it is out of phase
      # with the proxy check-routes interval of five minutes
      every: 660
      timeout: 600
      # maxAge is 3 hours: 3 * 3600 = 10800
      maxAge: 10800
    singleuser:
      serviceAccountName: daskkubernetes
      # start jupyter notebook
      cmd: jupyter-lab
      cloudMetadata:
        enabled: true
      cpu:
        limit: 4
        guarantee: 1
      memory:
        limit: 26G
        guarantee: 4G
    hub:
      resources:
        requests:
          cpu: "0.25"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 1Gi

