binderhub:
  ingress:
    hosts:
      - binder.pangeo.io
  hub:
    url: https://hub.binder.pangeo.io
  jupyterhub:
    ingress:
      hosts:
        - hub.binder.pangeo.io
      tls:
        - secretName: kubelego-tls-jupyterhub-binder
          hosts:
            - hub.binder.pangeo.io
