binderhub:
  config:
    BinderHub:
      use_registry: true
      image_prefix: gcr.io/pangeo-181919/pangeo-binder
      build_image: jupyter/repo2docker:9766c954
  template:
    path: "/etc/binderhub/templates/templates"
    static:
      path: "/etc/binderhub/templates/static"
      urlPrefix: extra_static/
  initContainers:
    - name: git-clone-templates
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --branch=master
        - --
        - https://github.com/pangeo-data/pangeo-custom-binderhub-templates.git
        - /etc/binderhub/templates
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: custom-templates
          mountPath: /etc/binderhub/templates
  extraVolumes:
    - name: custom-templates
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-templates
      mountPath: /etc/binderhub/templates

  jupyterhub:
    cull:
      # cull every 11 minutes so it is out of phase
      # with the proxy check-routes interval of five minutes
      every: 660
      timeout: 600
      # maxAge is 3 hours: 3 * 3600 = 10800
      maxAge: 10800
    singleuser:
      # start jupyter notebook
      cmd: jupyter-lab
      cloudMetadata:
        enabled: true
      cpu:
        limit: 4
        guarantee: 1
      memory:
        limit: 26G
        guarantee: 4G
    hub:
      resources:
        requests:
          cpu: "0.25"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 1Gi
    proxy:
      chp:
        resources:
          requests:
            memory: 512Mi
            cpu: "0.25"
          limits:
            memory: 512Mi
            cpu: "0.5"
      nginx:
        resources:
          requests:
            memory: 1Gi
            cpu: "0.25"
          limits:
            memory: 1Gi
            cpu: 1
