binderhub:
  config:
    BinderHub:
      hub_url: https://hub.staging.binder.pangeo.io
      image_prefix: gcr.io/pangeo-181919/staging-

  ingress:
    hosts:
      - staging.binder.pangeo.io

  jupyterhub:
    ingress:
      hosts:
        - hub.staging.binder.pangeo.io
      tls:
        - secretName: kubelego-tls-jupyterhub-staging
          hosts:
            - hub.staging.binder.pangeo.io

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 35.226.51.206
