projectName: pangeo-binder-staging

binderhub:
  config:
    BinderHub:
      build_node_selector:
        cloud.google.com/gke-nodepool: jupyter-pool
      hub_url: https://hub.staging.binder.pangeo.io
      image_prefix: gcr.io/pangeo-181919/staging-

  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool

  ingress:
    hosts:
      - staging.binder.pangeo.io

  dind:
    hostLibDir: /var/lib/dind/staging
    hostSocketDir: /var/run/dind/staging

  jupyterhub:
    singleuser:
      nodeSelector:
        cloud.google.com/gke-nodepool: jupyter-pool
    hub:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
    proxy:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
    ingress:
      hosts:
        - hub.staging.binder.pangeo.io
      tls:
        - secretName: kubelego-tls-jupyterhub-staging
          hosts:
            - hub.staging.binder.pangeo.io

kube-lego:
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 35.224.187.103
