projectName: pangeo-binder-staging

binderhub:
  config:
    BinderHub:
      build_node_selector:
        hub.jupyter.org/node-purpose: user
      hub_url: https://hub.staging.binder.pangeo.io
      image_prefix: gcr.io/pangeo-181919/staging-

  nodeSelector:
    hub.jupyter.org/node-purpose: core

  ingress:
    hosts:
      - staging.binder.pangeo.io

  dind:
    hostLibDir: /var/lib/dind/staging
    hostSocketDir: /var/run/dind/staging

  jupyterhub:
    proxy:
      nodeSelector:
        hub.jupyter.org/node-purpose: core
    ingress:
      hosts:
        - hub.staging.binder.pangeo.io
      tls:
        - secretName: kubelego-tls-jupyterhub-staging
          hosts:
            - hub.staging.binder.pangeo.io

kube-lego:
  nodeSelector:
    hub.jupyter.org/node-purpose: core

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 35.224.187.103
