{{- if .Values.rbac.enabled -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pangeo
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: pangeo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pangeo
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: pangeo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: [""]
  verbs: [""]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pangeo
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: pangeo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: pangeo
roleRef:
  kind: Role
  name: pangeo
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
